config/routes.rb
Rails.application.routes.draw do

  root 'workout#index'

  get 'workout/options'

  get 'workout/results/:workout' => 'workout#results', :as => "results"

  get 'workout_controller/index'

  get 'workout_controller/results'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/workout_controller.rb
class WorkoutController < ApplicationController
  before_action :set_workouts

  def set_workouts
   @workouts = {
      chest_triceps: ['Chest', 'Triceps'],
      back_biceps: ['Back', 'Biceps'],
      chest_back: ['Chest', 'Back'],
      shoulders_abs: ['Shoulders', 'Abs'],
      chest: ['Chest'],
      back: ['Back'],
      arms: ['Triceps', 'Biceps'],
      shoulders: ['Shoulders'],
      abs: ['Abs'],
      legs: ['Legs'],
      full_body: ['Full Body'],
    }


    @workout_names = {
      chest_triceps: "Chest & Triceps",
      back_biceps: "Back & Biceps",
      chest_back: "Chest & Back",
      shoulders_abs: "Shoulders & Abs",
      chest: "Chest",
      back: "Back",
      arms: "Biceps & Triceps",
      shoulders: "Shoulders",
      abs: "Abs",
      legs: "Legs",
      full_body: "Full Body",
    }
  end

  def index
  	@dropdown_options = [
      ["I didn't workout", :no_workout],
	  	["Chest & Triceps", :chest_triceps], 
	  	["Back & Biceps", :back_biceps], 
	  	["Chest & Back", :chest_back],
	  	["Shoulders & Abs", :shoulders_abs],
	  	["Chest", :chest], 
	  	["Back", :back],
	  	["Arms", :arms], 
	  	["Shoulders", :shoulders], 
	  	["Abs", :abs],
	  	["Legs", :legs],
	  	["Full Body", :full_body],
	]
  end

  def options

    exclusions = {
      no_workout: [],
      chest_triceps: ['Chest', 'Triceps'],
      back_biceps: ['Back', 'Biceps'],
      chest_back: ['Chest', 'Back'],
      shoulders_abs: ['Shoulders', 'Abs', 'Chest'],
      chest: ['Chest', 'Shoulders'],
      back: ['Back'],
      arms: ['Triceps', 'Chest', 'Biceps', 'Back'],
      shoulders: ['Shoulders', 'Chest'],
      abs: ['Abs'],
      legs: ['Legs'],
      full_body: ['Full Body'],
    }

    exclude_muscle_groups = exclusions[params[:workout_1].to_sym] | exclusions[params[:workout_2].to_sym]

    @resulting_workouts =[]

    @workouts.each do |workout, groups|
      if (groups & exclude_muscle_groups).empty?
        @resulting_workouts.push(workout)
      end
    end
  end


  def results
    workout = params[:workout].to_sym

  	muscle_groups = @workouts[workout]

    @workout_name = @workout_names[workout]
    

    if workout == :full_body
     @exercises = Exercise.all.order('RANDOM()').limit(8)
  
    else
	   @exercises = Exercise.where(muscle_group: muscle_groups, high_intensity: false).order('RANDOM()').limit(6)

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workout_helper.rb
module WorkoutHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlvaroFitnessApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" class="navbar-left"><%= image_tag "logo.PNG", width: 100%></a>
    </div>
</nav>

<div class="container">
	<%= yield %>
</div>
  </body>
</html>

app/views/workout/index.html.erb
<div class="jumbotron" class="container">ç

<h2>Welcome!</h2>
  <p>Let me build you the perfect workout according to the body parts you worked the last two days.</p>


<%= form_tag(workout_options_path, method: "get") do %>

<div class="form-group">
	<label> What did you workout 2 days ago?</label><br>
	<%= select_tag(:workout_2, options_for_select(@dropdown_options), {prompt: 'Select Muscle Group'})%>
</div>

<div class="form-group">
	<label> What did you workout yesterday?</label><br>
	<%= select_tag(:workout_1, options_for_select(@dropdown_options), {prompt: 'Select Muscle Group'})%>
</div>

<div class="form-group">
	<label> What kind of workout do you want to do?</label><br>
	<%= select_tag(:type_opt, options_for_select([["Muscle Building", 1], ["HIIT(High Intensity Interval Training", 2]]),{prompt: 'Select Type of Workout'})%>
</div>

<%= submit_tag("Check Results") %>
<% end %>
</div>

app/views/workout/options.html.erb
<div class="jumbotron" class="container">

<h3>Great! Now let's take a look at the muscle groups you can workout today.</h3>
<label>Which one do you feel like doing?</label>

<% @resulting_workouts.each do |workout| %>
<li><%=link_to @workout_names[workout], results_path(workout) %></li> 

<% end %>
</div>

app/views/workout/results.html.erb
<div class="container">

<h2>Time to put in the work!</h2>

<table style="width:100%">
  <tr>
    <th>Exercise</th>
    <th>Sets</th> 
    <th>Reps</th>
    <th>Weight</th>
    <th>Rest Time</th>
    <th>Notes</th>
  </tr>

  <% @exercises.each do |exercise| %>

  <tr>
    <th><%= exercise.name %></th>
    <td>3</td> 
    <td>8-15</td>
    <td></td>
    <td>90 sec</td>
    <td></td>
  </tr>
  <% end %>

</table>



</div>